# Generated by Django 4.1.5 on 2023-01-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='default_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(max_length=1001)),
                ('d_img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='GetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
    ]
